SRC		=	main.cpp Contact.cpp PhoneBook.cpp
OBJ		=	$(SRC:.cpp=.o)
NAME	=	phonebook
HEADER	=	Contact.hpp PhoneBook.hpp

all: $(NAME)

$(NAME): $(OBJ)
	@c++ -Wall -Wextra -Werror -std=c++98 $(OBJ) -o $(NAME)

%.o: %.cpp
	@c++ -Wall -Wextra -Werror -std=c++98 -c $< -o $@

clean:
	@rm -f $(OBJ)

fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY: clean